const data = {
  products: [
    {
      name: "Cafe Especial Cafetalero",
      slug: "Cafe-Especial-Cafetalero",
      category: "Molido",
      image:
        "/images/ProductPage/Inventario/Molido/CafeEspecialCafetalero.webp",
      price: 35,
      countInStock: 20,
      brand: "Nescafe",
      rating: 3.8,
      numReviews: 10,
      description: "Cafe de buena calidad, colombiano",
    },
    {
      name: "Cafe Especial Flor de Fruto",
      slug: "Cafe-Especial-Flor-De-Fruto",
      category: "Molido",
      image: "/images/ProductPage/Inventario/Molido/CafeEspecialFlorFruto.webp",
      price: 28,
      countInStock: 20,
      brand: "Nescafe",
      rating: 4.0,
      numReviews: 10,
      description: "Cafe de buena calidad, colombiano",
    },
    {
      name: "Cafe Especial Libre",
      slug: "Cafe-Especial-Libre",
      category: "Molido",
      image: "/images/ProductPage/Inventario/Molido/CafeEspecialLibre.webp",
      price: 20,
      countInStock: 10,
      brand: "Nescafe",
      rating: 3.5,
      numReviews: 10,
      description: "Cafe de buena calidad, colombiano",
    },
    {
      name: "Cafe Especial Peligro",
      slug: "Cafe-Especial-Peligro",
      category: "Molido",
      image: "/images/ProductPage/Inventario/Molido/CafeEspecialPeligro.webp",
      price: 42,
      countInStock: 30,
      brand: "Nescafe",
      rating: 4.2,
      numReviews: 10,
      description: "Cafe de buena calidad, colombiano",
    },
  ],
};
export default data;
